# online-judge common config

############################# jetty访问路径、端口 start #############################
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# jetty访问路径、端口 end ###############################


################################ spring config start ###############################
spring:
  profiles:
    active: dev
################################ spring config end #################################