# online-judge product config

################################ datasource connector config start ###############################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinejudge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123
################################ datasource connector config end #################################